name: Build and Publish Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - release/build_wheel
  pull_request:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up JDK ${{ inputs.java }}
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
          pip install -r dev/dev-requirements.txt
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
      - name: Publish wheels
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
